package org.tfortin.gigit.model.dao;

// Generated 4 avr. 2013 02:35:38 by Hibernate Tools 3.4.0.CR1

/**
 * Bookmark generated by hbm2java
 */
public class Bookmark implements java.io.Serializable {

	private long id;
	private User user;
	private String project;

	public Bookmark() {
	}

	public Bookmark(long id, User user) {
		this.id = id;
		this.user = user;
	}

	public Bookmark(long id, User user, String project) {
		this.id = id;
		this.user = user;
		this.project = project;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

}
