package org.tfortin.gigit.model.dao;

// Generated 4 avr. 2013 02:35:38 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * History generated by hbm2java
 */
public class History implements java.io.Serializable {

	private static final long serialVersionUID = 3135252788058767924L;
	private Long id;
	private User user;
	private String search;
	private Date searchTime;
	private Boolean userSearch;

	public History() {
	}

	public History(Long id, User user) {
		this.id = id;
		this.user = user;
	}

	public History(Long id, User user, String search, Date searchTime,
			Boolean userSearch) {
		this.id = id;
		this.user = user;
		this.search = search;
		this.searchTime = searchTime;
		this.userSearch = userSearch;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getSearch() {
		return this.search;
	}

	public void setSearch(String search) {
		this.search = search;
	}

	public Date getSearchTime() {
		return this.searchTime;
	}

	public void setSearchTime(Date searchTime) {
		this.searchTime = searchTime;
	}

	public Boolean getUserSearch() {
		return this.userSearch;
	}

	public void setUserSearch(Boolean userSearch) {
		this.userSearch = userSearch;
	}

}
